### ISSUE TITLE
Updated version

### ISSUE THREAD

**Issue by johanntt** [archimatetool/ArchiModels#1]
Hi
Thanks for your work and having the examples in here.  Are you going to update the model for ArchiMate 3.0?

Regards
Jóhann

**Comment by Phillipus** [comment]
Yes, I will once the exchange format is updated.

Phil

**Comment by teterkin** [comment]
@Phillipus Thank you for your work!!!
Looks like format is updated: https://www2.opengroup.org/ogsys/catalog/C174

**Comment by teterkin** [comment]
And also they have ArchiMetal and ArchiSurance examples there:
https://www2.opengroup.org/ogsys/publications/viewDocument.html?publicationid=15240&documentid=14684

**Comment by sumanneethipudi** [comment]
> 
> 
> Yes, I will once the exchange format is updated.
> 
> Phil

Thanks phil for the xmls. However, when i am trying to open archinsurance.xml using archi 4.7 version, it is throwing an error. Any help here is much appreciated.

Regards
Suman

**Comment by jbsarrodie** [comment]
Hi. Are you sure you imported the model and not try to open it as if it was a native file?

**Comment by Phillipus** [comment]
This is an older format file from Exchange Format 2.1 so won't import. I didn't update the file.

This repository is no longer maintained, so it might be better to archive it, and host these models somewhere else, perhaps the ArchiMate Community site?

**Comment by Phillipus** [comment]
Closing this issue as I'm going to archive this repository, it hasn't been updated in 5 years. 😮
